package bootloader

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// InstallGRUB installs GRUB bootloader to the specified device
func InstallGRUB(mountpoint, device, grubCmd string) error {
	// Prepare grub-install arguments
	args := []string{
		"--target=i386-pc",
		"--boot-directory=" + filepath.Join(mountpoint, "boot"),
		"--force",
		device,
	}

	cmd := exec.Command(grubCmd, args...)
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to install GRUB with %s: %v", grubCmd, err)
	}

	return nil
}

// WriteGRUBConfig writes a GRUB configuration file
func WriteGRUBConfig(mountpoint, grubPrefix string) error {
	// Determine the correct boot directory based on grub prefix
	var bootDir string
	if strings.Contains(grubPrefix, "grub2") {
		bootDir = filepath.Join(mountpoint, "boot", "grub2")
	} else {
		bootDir = filepath.Join(mountpoint, "boot", "grub")
	}

	// Ensure boot directory exists
	if err := os.MkdirAll(bootDir, 0755); err != nil {
		return fmt.Errorf("failed to create boot directory %s: %v", bootDir, err)
	}

	// Write grub.cfg
	grubCfgPath := filepath.Join(bootDir, "grub.cfg")
	grubConfig := generateGRUBConfig(grubPrefix)

	if err := os.WriteFile(grubCfgPath, []byte(grubConfig), 0644); err != nil {
		return fmt.Errorf("failed to write GRUB config to %s: %v", grubCfgPath, err)
	}

	return nil
}

// DetectGRUBPrefix detects whether to use grub or grub2 prefix from command name
func DetectGRUBPrefix(grubCmd string) string {
	if strings.Contains(grubCmd, "grub2") {
		return "grub2"
	}
	return "grub"
}

// generateGRUBConfig generates a basic GRUB configuration for Windows USB
func generateGRUBConfig(grubPrefix string) string {
	return `# GRUB configuration for Windows USB
# Generated by WoeUSB-ng

set timeout=10
set default=0

menuentry "Windows" {
    insmod part_msdos
    insmod ntfs
    insmod search_fs_uuid
    insmod chain
    search --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1
    chainloader +1
}

menuentry "Windows (fallback)" {
    insmod part_msdos
    insmod fat
    insmod search_fs_uuid
    insmod chain
    search --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1
    chainloader +1
}
`
}

// InstallGRUBWithConfig installs GRUB and writes configuration in one step
func InstallGRUBWithConfig(mountpoint, device, grubCmd string) error {
	// Install GRUB
	if err := InstallGRUB(mountpoint, device, grubCmd); err != nil {
		return fmt.Errorf("GRUB installation failed: %v", err)
	}

	// Detect prefix and write config
	grubPrefix := DetectGRUBPrefix(grubCmd)
	if err := WriteGRUBConfig(mountpoint, grubPrefix); err != nil {
		return fmt.Errorf("GRUB configuration failed: %v", err)
	}

	return nil
}

// CheckGRUBInstallation verifies that GRUB was installed correctly
func CheckGRUBInstallation(mountpoint, grubPrefix string) error {
	// Check for boot directory
	var bootDir string
	if grubPrefix == "grub2" {
		bootDir = filepath.Join(mountpoint, "boot", "grub2")
	} else {
		bootDir = filepath.Join(mountpoint, "boot", "grub")
	}

	if _, err := os.Stat(bootDir); os.IsNotExist(err) {
		return fmt.Errorf("GRUB boot directory not found: %s", bootDir)
	}

	// Check for grub.cfg
	grubCfgPath := filepath.Join(bootDir, "grub.cfg")
	if _, err := os.Stat(grubCfgPath); os.IsNotExist(err) {
		return fmt.Errorf("GRUB configuration file not found: %s", grubCfgPath)
	}

	return nil
}

// GetGRUBVersion attempts to get the version of the GRUB command
func GetGRUBVersion(grubCmd string) (string, error) {
	cmd := exec.Command(grubCmd, "--version")
	output, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("failed to get GRUB version: %v", err)
	}

	return strings.TrimSpace(string(output)), nil
}
